routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\{
    DashboardController,
    AuthController,
};

use App\Http\Controllers\LogoBrandingController;
use App\Http\Controllers\DesignFeedInstagramController;
use App\Http\Controllers\DigitalMarketingController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SMMController;
use App\Http\Controllers\MarketingCommunicationsController;

use App\Http\Controllers\AdvantageController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DetailPageController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\DetailServiceController;
use App\Http\Controllers\JasaController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\PackageFeatureController;
use App\Http\Controllers\PortofolioController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TestimonialController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SitemapController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');
Route::get('/check', [HomeController::class, 'check'])->name('home.check');

Route::get('/articles', [PostsController::class, 'index'])->name('posts.index');

Route::get('/layanan/{slug}', [DetailPageController::class, 'index'])->name('detail_page.index');
Route::get('/article/{slug}', [PostController::class, 'index'])->name('post.index');

Route::get('/sitemap', [SitemapController::class, 'index']);

// FrontEnd UI/UX
    // Logo Branding
    // Route::get('/logobranding', [LogoBrandingController::class, 'index'])->name('logobranding.index');

   // Design Feed Instagram
    // Route::get('/designfeed', [DesignFeedInstagramController::class, 'index'])->name('designfeed.index');

    // Digital Marketing
    // Route::get('/digitalmarketing', [DigitalMarketingController::class, 'index'])->name('digitalmarketing.index');

    // Social MM
    // Route::get('/smm', [SMMController::class, 'index'])->name('smm.index');

    // Marketing Communications
    // Route::get('/marketingcommunications', [MarketingCommunicationsController::class, 'index'])->name('marketing.index');

    // Login Dashboard
    Route::get('/auth/login', [AuthController::class, 'auth'])->name('auth.index');
    Route::post('/auth/process', [AuthController::class, 'process'])->name('auth.process');

// Disini untuk admin
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'dashboard']);

    // Rute Semua Layanan

        // Slug Service 
        Route::get('/dashboard/layanan/service/makeSlug', [ServiceController::class, 'makeSlug'])->middleware('auth');

        // Service
        Route::resource('/dashboard/layanan/service', ServiceController::class);
        Route::post('/dashboard/layanan/service/data', [ServiceController::class, 'data'])->name('service.data');

        // Service - Sub (What are the Service are)
        Route::resource('/dashboard/layanan/jasa', JasaController::class);
        Route::post('/dashboard/layanan/jasa/data', [JasaController::class, 'data'])->name('jasa.data');

         // Detail Services
         Route::resource('/dashboard/layanan/detail_layanan', DetailServiceController::class);
         Route::post('/dashboard/layanan/detail_layanan/data', [DetailServiceController::class, 'data'])->name('detail_service.data');
         Route::get('/dashboard/layanan/detail_layanan/{id}/edit', [DetailServiceController::class, 'ubah'])->name('detail_layanan.ubah');
         Route::delete('/dashboard/layanan/detail_layanan/{id}/hapus', [DetailServiceController::class, 'hapus'])->name('detail_service.hapus');
    //

    // Article
    Route::resource('/dashboard/article', ArticleController::class);
    Route::post('/dashboard/article/table', [ArticleController::class, 'table'])->name('article.table');
        
    // Testimonial
    Route::resource('/dashboard/testimonial', TestimonialController::class);
    Route::post('/dashboard/testimonial/data', [TestimonialController::class, 'data'])->name('testimonial.data');

    // Portofolio
    Route::resource('/dashboard/portofolio', PortofolioController::class);
    Route::post('/dashboard/portofolio/data', [PortofolioController::class, 'data'])->name('portofolio.data');

    //Package
    Route::resource('dashboard/package', PackageController::class);
    Route::post('/dashboard/package/data', [PackageController::class, 'data'])->name('package.data');
    //Feature
    Route::resource('dashboard/feature', FeatureController::class);
    Route::post('/dashboard/feature/data', [FeatureController::class, 'data'])->name('feature.data'); 

    // Client
    Route::resource('/dashboard/client', ClientController::class);
    Route::post('/dashboard/client/data', [ClientController::class, 'data'])->name('client.data');

    //Feature
    Route::resource('dashboard/feature', FeatureController::class);
    Route::post('/dashboard/feature/data', [FeatureController::class, 'data'])->name('feature.data');

    //Advantage or Previllege
    Route::resource('/dashboard/advantage', AdvantageController::class);
    Route::post('/dashboard/advantage/data', [AdvantageController::class, 'data'])->name('advantage.data');

    //Categories
    // Route::resource('/dashboard/categories', CategoriesController::class);
    // Route::get('/dashboard/categories/{id}/edit', [CategoriesController::class, 'edid'])->name('categories.edid');
    // Route::put('/dashboard/categories/update', [CategoriesController::class, 'apded'])->name('categories.apded');
    // Route::post('/dashboard/categories/data', [CategoriesController::class, 'data'])->name('categories.data');
    // Route::delete('/dashboard/categories/{id}/hapus', [CategoriesController::class, 'hapus'])->name('categories.hapus');
    
     // Category
     Route::resource('dashboard/categories', CategoryController::class);
     Route::post('/dashboard/categories/data', [CategoryController::class, 'data'])->name('category.data');
 

    // Article
    Route::resource('/dashboard/article', ArticleController::class);
    Route::post('/dashboard/article/data', [ArticleController::class, 'data'])->name('article.data');
        // Slug Service 
        Route::get('/dashboard/article/articleSlug', [ServiceController::class, 'articleSlug'])->middleware('auth');

    // User
    Route::resource('dashboard/user', UserController::class);
    Route::post('/dashboard/user/data', [UserController::class, 'data'])->name('user.data');

    //Setting
    Route::resource('/dashboard/setting', SettingController::class);
    Route::put('/dashboard/setting/{id}/setting_home', [SettingController::class, 'updateHome'])->name('setting.updateHome');
    Route::put('/dashboard/setting/{id}/setting_dashboard', [SettingController::class, 'updateDashboard'])->name('setting.updateDashboard');

    //Logout
    Route::get('/auth/logout', [AuthController::class, 'logout'])->name('auth.logout');    
    
});

app/Models/Advantage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Advantage extends Model
{
    use HasFactory;

    protected $table = 'advantage';
    protected $primaryKey = 'id';
    protected $guarded = [];

    public function module() 
    {
        return $this->belongsToMany(Module::class, 'module');
    } 
}

app/Http/Controllers/AdvantageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Advantage;
use App\Models\SettingDashboard;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AdvantageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $advantage = Advantage::all();
        // $setting = SettingDashboard::first();

        return view('advantage.index', compact('advantage'));
    }

    public function data()
    {
        $advantage = Advantage::orderBy('id', 'desc')->get();

        return datatables()
            ->of($advantage)
            ->addIndexColumn()
            ->addColumn('image', function($advantage) {
                return '
                    <img width="90%" class="rounded" src="'. asset('storage/'.$advantage->image) .'">
                ';
            })
            ->addColumn('advantage', function($advantage) {
                return $advantage->advantage;
            })
            ->addColumn('description', function($advantage) {
                return $advantage->description;
            })
            ->addColumn('created', function($advantage) {
                return tanggal($advantage->created_at);
            })
            ->addColumn('action', function ($advantage) {
                return '
                    <a href="'. route('advantage.edit', $advantage->id) .'" class="btn btn-xs bg-warning"><i class="fa-solid fa-pen-to-square"></i></a>
                    <button onclick="deleteData(`'. route('advantage.destroy', $advantage->id) .'`)" class="btn btn-xs btn-danger btn-flat delete"><i class="fa-solid fa-trash-can"></i></button>
                ';
            })
            ->rawColumns(['action', 'image'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('advantage.create', [
            'advantage' => Advantage::all(),
            // 'setting' =>  SettingDashboard::first()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request->file('image')->store('advantage');

        $validate = $request->validate([
            'image' => 'image|file|max:12000',
            'advantage' => 'required|min:3|max:100',
            'description' => 'required|max:2500'
        ]);

        if($request->file('image')) {
            $validate['image'] = $request->file('image')->store('advantage');
        }

        $image = $validate['image'];
        $advantage = $request['advantage'];
        $description = $request['description'];

        $save = New Advantage();
        $save->image = $image;
        $save->advantage = $advantage;
        $save->description = $description;
        $save->save();

        return redirect()->route('advantage.index')->with(['success' => 'Berhasil Disimpan!']);
        // return redirect('/dashboard/advantage')->with('success', 'Keunggulan baru berhasil ditambah'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Advantage  $advantage
     * @return \Illuminate\Http\Response
     */
    public function show(Advantage $advantage)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Advantage  $advantage
     * @return \Illuminate\Http\Response
     */
    public function edit(Advantage $advantage)
    {
        return view('advantage.edit', [
            'previllege' => $advantage,
            'advantage' => Advantage::all(),
            // 'setting' =>  SettingDashboard::first()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Advantage  $advantage
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Advantage $advantage)
    {
        $rules = $request->validate([
            'image' => 'image|file|max:12000',
            'advantage' => 'min:3|max:100',
            'description' => 'max:2500'
        ]);

        if($request->file('image')) {
            if($request->oldImage) {
                Storage::delete($request->oldImage);
            }
            $rules['image'] = $request->file('image')->store('advantage');
        }
        
        
        Advantage::where('id', $advantage->id)->update($rules);
        return redirect()->route('advantage.index')->with(['success' => 'Berhasil Diperbarui!']);
        // return redirect('/dashboard/advantage')->with('success', 'Keunggulan berhasil diupdate'); 

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Advantage  $advantage
     * @return \Illuminate\Http\Response
     */
    public function destroy(Advantage $advantage)
    {
        if($advantage->image) {
            Storage::delete($advantage->image);
        //     Public::delete($advantage->image);
            // File::delete(public_path('advantage-images/'. $advantage->image));
        }

        Advantage::destroy($advantage->id);
        return redirect()->route('advantage.index')->with(['success' => 'Berhasil Dihapus!']);
        // return redirect('/dashboard/advantage')->with('success', 'Keunggulan berhasil dihapus');

    }
}

resources/views/advantage/create.blade.php
@extends('admin.main')

@section('content')
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title mb-1"><b>Layanan</b></h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Layanan</li>
                        <li class="breadcrumb-item active"><a href="/dashboard/advantage/">Keunggulan</a></li>
                        <li class="breadcrumb-item active">Form Keunggulan</li>
                    </ol>
                </div><!--end col-->
            </div><!--end row-->                                                              
        </div><!--end page-title-box-->
    </div><!--end col-->
</div><!--end row-->
<div class="col-md-12 pt-3 pb-2 mb-3" style="background-color: white;">
    <div class="box">
        <div class="col-lg-8" style="margin: auto">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Form Keunggulan</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route('advantage.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="image" class="form-label">Gambar</label>
                            <input type="file" class="form-control @error('image') is-invalid @enderror" id="image"
                                name="image" value="{{ old('image') }}" required onchange="previewImage()">
                            <img class="img-preview img-fluid my-3 col-sm-5">
                            @error('image')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="advantage" class="form-label">Keunggulan</label>
                            <input class="form-control @error('advantage') is-invalid @enderror" rows="3" id="advantage"
                                name="advantage" value="{{ old('advantage') }}" required autofocus>
                            @error('advantage')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="description" class="form-label">Deskripsi</label>
                            <textarea class="form-control @error('description') is-invalid @enderror" id="description" rows="3"
                                name="description" value="{{ old('description') }}" required></textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="/dashboard/advantage" class="btn btn-danger">Kembali</a>
                    </form>                                           
                </div><!--end card-body-->
            </div><!--end card-->
        </div><!--end col-->
    </div>
</div>
@endsection

@push('script')
<script>
    function previewImage() {
        const image = document.querySelector('#image');
        const imgPreview = document.querySelector('.img-preview');

        imgPreview.style.display = 'block';

        const oFReader = new FileReader();
        oFReader.readAsDataURL(image.files[0]);

        oFReader.onload = function(oFREvent) {
        imgPreview.src = oFREvent.target.result;
        }
    }
</script>
@endpush

resources/views/advantage/edit.blade.php
@extends('admin.main')

@section('content')
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title mb-1"><b>Layanan</b></h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Layanan</li>
                        <li class="breadcrumb-item active"><a href="/dashboard/advantage/">Keunggulan</a></li>
                        <li class="breadcrumb-item active">Form Keunggulan</li>
                    </ol>
                </div><!--end col-->
            </div><!--end row-->                                                              
        </div><!--end page-title-box-->
    </div><!--end col-->
</div><!--end row-->
<div class="col-md-12 pt-3 pb-2 mb-3" style="background-color: white;">
    <div class="box">
        <div class="col-lg-8" style="margin: auto">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Form Keunggulan</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route('advantage.update', $previllege->id) }}" method="post"
                        enctype="multipart/form-data">
                        @method('put')
                        @csrf
                        <div class="form-group">
                            <label for="image" class="form-label">Gambar</label>
                            <input type="file" class="form-control @error('image') is-invalid @enderror" id="image"
                                name="image" onchange="previewImage()" value="{{ old('image', $previllege->image) }}">
                            <input type="hidden" name="oldImage" id="oldImage" value="{{ $previllege->image }}">
                            @if($previllege->image)
                            <img src="{{ asset('storage/' . $previllege->image) }}"
                                class="img-preview img-fluid my-3 col-sm-5 d-block">
                            @else
                            <img class="img-preview img-fluid my-3 col-sm-5">
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="advantage" class="form-label">Keunggulan</label>
                            <input class="form-control @error('advantage') is-invalid @enderror" rows="3" id="advantage"
                                name="advantage" value="{{ old('advantage', $previllege->advantage ) }}" autofocus>
                            @error('advantage')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="description" class="form-label">Deskripsi</label>
                            <textarea class="form-control @error('description') is-invalid @enderror" id="description" rows="3"
                                name="description">{{ old('description', $previllege->description) }}</textarea>
                            @error('description')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="/dashboard/advantage" class="btn btn-danger">Kembali</a>
                    </form>                                           
                </div><!--end card-body-->
            </div><!--end card-->
        </div><!--end col-->
    </div>
</div>
@endsection

@push('script')
<script>
    function previewImage() {
        const image = document.querySelector('#image');
        const imgPreview = document.querySelector('.img-preview');

        imgPreview.style.display = 'block';

        const oFReader = new FileReader();
        oFReader.readAsDataURL(image.files[0]);

        oFReader.onload = function(oFREvent) {
        imgPreview.src = oFREvent.target.result;
        }
    }
</script>
@endpush

resources/views/advantage/index.blade.php
@extends('admin.main')

@section('content')
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title mb-1"><b>Layanan</b></h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active"><a href="/dashboard">Dashboard</a></li>
                        <li class="breadcrumb-item">Layanan</li>
                        <li class="breadcrumb-item active">Keunggulan</li>
                    </ol>
                </div><!--end col-->
            </div><!--end row-->                                                              
        </div><!--end page-title-box-->
    </div><!--end col-->
</div><!--end row-->
<div class="col-md-12 p-2 mb-3" style="background-color: white">

        <div class="box">
            <div class="box-header with-border mx-2">
                <h2 class="my-5 text-center">Keunggulan</h2>
                <a href="/dashboard/advantage/create" class="btn btn-outline-dark mb-3 p-2">
                    Tambah Baru
                    <span data-feather="plus-circle"></span>
                </a>
            </div>

            <div class="box-body table-responsive">
                <table class="table table-bordered table-advantage">
                    <thead>
                        <tr>
                            <th scope="col" class="text-center table-default" style="color:black;" width="6%">No</th>
                            <th width="20%" scope="col" class="text-center table-default" style="color:black;">Gambar
                            </th>
                            <th scope="col" class="text-center table-default" style="color:black;">Keunggulan</th>
                            <th scope="col" class="text-center table-default" style="color:black;">Deskripsi</th>
                            <th width="15%" scope="col" class="text-center table-default" style="color:black;">Created
                                At</th>
                            <th width="10%" scope="col" class="text-center table-default" style="color:black;"> <i
                                    class="fas fa-regular fa-gears"></i> </th>
                        </tr>
                    </thead>

                </table>
            </div>

    </div>
</div>
@endsection

@push('script')
<script>

    function messageSuccess() {
        alert(
            Swal.fire({
                icon: 'success',
                title: 'Your work has been saved',
                showConfirmButton: false,
                timer: 1500
            })
        );
    }


    var time = document.getElementById("alert");

    setTimeout(function(){
        time.style.display = "none";
    }, 3000);   

    function previewImage() {
        const image = document.querySelector('#image');
        const imgPreview = document.querySelector('.img-preview');

        imgPreview.style.display = 'block';

        const oFReader = new FileReader();
        oFReader.readAsDataURL(image.files[0]);

        oFReader.onload = function(oFREvent) {
        imgPreview.src = oFREvent.target.result;
        }
    }

    let table;
        table = $('.table-advantage').DataTable({
        processing: true,
        responsive: true,
        autoWidth: false,
        serverSide: true,
        ajax: {
            url: "{{ route('advantage.data') }}",
            type: "POST",
            data: {  
                _token: '{{ csrf_token() }}'
            }
        },
        columns: [
            {data:'DT_RowIndex', searchable: false, sortable: false},
            {data:'image'},
            {data:'advantage'},
            {data:'description'},
            {data:'created'},
            {data:'action', searchable: false, sortable: false},
        ]
    });

    function deleteData(url) {
        Swal.fire({
            title: 'Hapus Keunggulan yang dipilih?',
            icon: 'question',
            iconColor: '#DC3545',
            showDenyButton: true,
            denyButtonColor: '#838383',
            denyButtonText: 'Batal',
            confirmButtonText: 'Hapus',
            confirmButtonColor: '#DC3545'
            }).then((result) => {
            if (result.isConfirmed) {
                $.post(url, {
                    '_token': $('[name=csrf-token]').attr('content'),
                    '_method': 'delete'
                })
                .done((response) => {
                    Swal.fire({
                        title: 'Sukses!',
                        text: 'Keunggulan berhasil dihapus',
                        icon: 'success',
                        confirmButtonText: 'Lanjut',
                        confirmButtonColor: '#28A745'
                        ,
                    }) 
                    table.ajax.reload();
                })
                .fail((errors) => {
                    Swal.fire({
                        title: 'Gagal!',
                        text: 'Keunggulan gagal dihapus',
                        icon: 'error',
                        confirmButtonText: 'Kembali',
                        confirmButtonColor: '#DC3545'
                        ,
                    })                       
                    return;
                });
            } else if (result.isDenied) {
                Swal.fire({
                    title: 'Keunggulan batal dihapus',
                    icon: 'warning'
                    ,
                })
            }
        })
    }
</script> 
@endpush