routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\{
    DashboardController,
    AuthController,
};

use App\Http\Controllers\LogoBrandingController;
use App\Http\Controllers\DesignFeedInstagramController;
use App\Http\Controllers\DigitalMarketingController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SMMController;
use App\Http\Controllers\MarketingCommunicationsController;

use App\Http\Controllers\AdvantageController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DetailPageController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\DetailServiceController;
use App\Http\Controllers\JasaController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\PackageFeatureController;
use App\Http\Controllers\PortofolioController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TestimonialController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SitemapController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');
Route::get('/check', [HomeController::class, 'check'])->name('home.check');

Route::get('/articles', [PostsController::class, 'index'])->name('posts.index');

Route::get('/layanan/{slug}', [DetailPageController::class, 'index'])->name('detail_page.index');
Route::get('/article/{slug}', [PostController::class, 'index'])->name('post.index');

Route::get('/sitemap', [SitemapController::class, 'index']);

// FrontEnd UI/UX
    // Logo Branding
    // Route::get('/logobranding', [LogoBrandingController::class, 'index'])->name('logobranding.index');

   // Design Feed Instagram
    // Route::get('/designfeed', [DesignFeedInstagramController::class, 'index'])->name('designfeed.index');

    // Digital Marketing
    // Route::get('/digitalmarketing', [DigitalMarketingController::class, 'index'])->name('digitalmarketing.index');

    // Social MM
    // Route::get('/smm', [SMMController::class, 'index'])->name('smm.index');

    // Marketing Communications
    // Route::get('/marketingcommunications', [MarketingCommunicationsController::class, 'index'])->name('marketing.index');

    // Login Dashboard
    Route::get('/auth/login', [AuthController::class, 'auth'])->name('auth.index');
    Route::post('/auth/process', [AuthController::class, 'process'])->name('auth.process');

// Disini untuk admin
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'dashboard']);

    // Rute Semua Layanan

        // Slug Service 
        Route::get('/dashboard/layanan/service/makeSlug', [ServiceController::class, 'makeSlug'])->middleware('auth');

        // Service
        Route::resource('/dashboard/layanan/service', ServiceController::class);
        Route::post('/dashboard/layanan/service/data', [ServiceController::class, 'data'])->name('service.data');

        // Service - Sub (What are the Service are)
        Route::resource('/dashboard/layanan/jasa', JasaController::class);
        Route::post('/dashboard/layanan/jasa/data', [JasaController::class, 'data'])->name('jasa.data');

         // Detail Services
         Route::resource('/dashboard/layanan/detail_layanan', DetailServiceController::class);
         Route::post('/dashboard/layanan/detail_layanan/data', [DetailServiceController::class, 'data'])->name('detail_service.data');
         Route::get('/dashboard/layanan/detail_layanan/{id}/edit', [DetailServiceController::class, 'ubah'])->name('detail_layanan.ubah');
         Route::delete('/dashboard/layanan/detail_layanan/{id}/hapus', [DetailServiceController::class, 'hapus'])->name('detail_service.hapus');
    //

    // Article
    Route::resource('/dashboard/article', ArticleController::class);
    Route::post('/dashboard/article/table', [ArticleController::class, 'table'])->name('article.table');
        
    // Testimonial
    Route::resource('/dashboard/testimonial', TestimonialController::class);
    Route::post('/dashboard/testimonial/data', [TestimonialController::class, 'data'])->name('testimonial.data');

    // Portofolio
    Route::resource('/dashboard/portofolio', PortofolioController::class);
    Route::post('/dashboard/portofolio/data', [PortofolioController::class, 'data'])->name('portofolio.data');

    //Package
    Route::resource('dashboard/package', PackageController::class);
    Route::post('/dashboard/package/data', [PackageController::class, 'data'])->name('package.data');
    //Feature
    Route::resource('dashboard/feature', FeatureController::class);
    Route::post('/dashboard/feature/data', [FeatureController::class, 'data'])->name('feature.data'); 

    // Client
    Route::resource('/dashboard/client', ClientController::class);
    Route::post('/dashboard/client/data', [ClientController::class, 'data'])->name('client.data');

    //Feature
    Route::resource('dashboard/feature', FeatureController::class);
    Route::post('/dashboard/feature/data', [FeatureController::class, 'data'])->name('feature.data');

    //Advantage or Previllege
    Route::resource('/dashboard/advantage', AdvantageController::class);
    Route::post('/dashboard/advantage/data', [AdvantageController::class, 'data'])->name('advantage.data');

    //Categories
    // Route::resource('/dashboard/categories', CategoriesController::class);
    // Route::get('/dashboard/categories/{id}/edit', [CategoriesController::class, 'edid'])->name('categories.edid');
    // Route::put('/dashboard/categories/update', [CategoriesController::class, 'apded'])->name('categories.apded');
    // Route::post('/dashboard/categories/data', [CategoriesController::class, 'data'])->name('categories.data');
    // Route::delete('/dashboard/categories/{id}/hapus', [CategoriesController::class, 'hapus'])->name('categories.hapus');
    
     // Category
     Route::resource('dashboard/categories', CategoryController::class);
     Route::post('/dashboard/categories/data', [CategoryController::class, 'data'])->name('category.data');
 

    // Article
    Route::resource('/dashboard/article', ArticleController::class);
    Route::post('/dashboard/article/data', [ArticleController::class, 'data'])->name('article.data');
        // Slug Service 
        Route::get('/dashboard/article/articleSlug', [ServiceController::class, 'articleSlug'])->middleware('auth');

    // User
    Route::resource('dashboard/user', UserController::class);
    Route::post('/dashboard/user/data', [UserController::class, 'data'])->name('user.data');

    //Setting
    Route::resource('/dashboard/setting', SettingController::class);
    Route::put('/dashboard/setting/{id}/setting_home', [SettingController::class, 'updateHome'])->name('setting.updateHome');
    Route::put('/dashboard/setting/{id}/setting_dashboard', [SettingController::class, 'updateDashboard'])->name('setting.updateDashboard');

    //Logout
    Route::get('/auth/logout', [AuthController::class, 'logout'])->name('auth.logout');    
    
});

resources/views/layanan/detail_layanan/create.blade.php
@extends('admin.main')

@section('content')
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title mb-1"><b>Layanan</b></h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Layanan</li>
                        <li class="breadcrumb-item active"><a href="/dashboard/layanan/detail_layanan">Detail Layanan</a></li>
                        <li class="breadcrumb-item active">Form Detail Layanan</li>
                    </ol>
                </div><!--end col-->
            </div><!--end row-->                                                              
        </div><!--end page-title-box-->
    </div><!--end col-->
</div><!--end row-->
<div class="col-md-12 pt-3 pb-2 mb-3" style="background-color: white;">
    <div class="box">
        <div class="col-lg-8" style="margin: auto">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Form Detail Layanan</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route('detail_layanan.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="service" class="form-label">Pilih Layanan</label>
                            <div class="input-group">
                                <select name="service" id="service" class="form-control mb-4">
                                    <option value="">-- Pilih Layanan --</option>
                                    @foreach ($service as $item )
                                        <option value="{{ $item->id }}">{{ $item->title }}</option>
                                    @endforeach
                                </select>
                            </div>
                            @error('service')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="mb-4 p-3" style="border: 1px dotted black;">
                            <p class="text-center " style="font-size:25px;">Form untuk bagian info halaman</p>
                            <br>
                            <div class="mb-2">
                                <label for="question" class="form-label">Custom title untuk Pertanyaan Mengenai Layanan</label>
                                <input type="text" class="form-control mb-3 @error('question') is-invalid @enderror" id="question" name="question" value="{{ old('question') }}" required maxlength="255">
                                @error('question')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                @enderror
                                <div class="mb-2">
                                    <label for="image" class="form-label">Gambar</label>
                                    <input type="file" class="form-control @error('image') is-invalid @enderror" id="image"
                                        name="image" value="{{ old('image') }}" required onchange="previewImage()">
                                    <img class="img-preview img-fluid my-3 col-sm-5">
                                    @error('image')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                
                                <div class="col-lg-12 mb-2">
                                    <div class="col-lg-12 mb-2">
                                        <label for="answer" class="form-label">Jawaban</label>
                                        @error('answer')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                        <input type="hidden" class="form-control" id="answer" name="answer" value="{{ old('answer') }}" required maxlength="255">
                                    <trix-editor input="answer"></trix-editor>
                                </div>
                                
                            </div>
                        </div>
                        <div class="form-group mt-4">
                            <label for="jasa" class="form-label">Detail Layanan</label>
                            <div class="input-group">
                                <select name="jasa[]" id="feature" multiple class="chosen-select form-control mb-4">
                                    @foreach ($jasa as $item)
                                        <option value="{{ $item->id }}">{{ $item->title }}</option>
                                    @endforeach
                                </select>
                            </div>
                            @error('jasa')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="advantage" class="form-label">Keunggulan</label>
                            <div class="input-group">
                                <select name="advantage[]" id="feature" multiple class="chosen-select form-control mb-4">
                                    @foreach ($advantage as $item)
                                        <option value="{{ $item->id }}">{{ $item->advantage }}</option>
                                    @endforeach
                                </select>
                            </div>
                            @error('advantage')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="package" class="form-label">Paket</label>
                            <div class="input-group">
                                <select name="package[]" id="feature" multiple class="chosen-select form-control mb-4">
                                    @foreach ($package as $item)
                                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                                    @endforeach
                                </select>
                                <span class="placeholder col-12 bg-light">MAX 3 Select : Kiri | Tengah | Kanan</span>
                            </div>
                            @error('package')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="/dashboard/layanan/detail_layanan" class="btn btn-danger">Kembali</a>
                    </form>                                           
                </div><!--end card-body-->
            </div><!--end card-->
        </div><!--end col-->
    </div>
</div>
@endsection

@push('script')
<script>

    $(document).ready(function () {
        $(".chosen-select-deselect").chosen({allow_single_deselect:true});
        $(".chosen-select").chosen({ max_selected_options:3});
        $(".chosen-select").bind("chosen:maxselected", function () { 
            let timerInterval
            Swal.fire({
                title: 'Max Selected is 3!',
                html: '<b></b>',
                timer: 1650,
                timerProgressBar: true,
                didOpen: () => {
                    Swal.showLoading()
                    const b = Swal.getHtmlContainer().querySelector('b')
                    timerInterval = setInterval(() => {
                    b.textContent = Swal.getTimerLeft()
                    }, 100)
                },
                willClose: () => {
                    clearInterval(timerInterval)
                }
                }).then((result) => {
                /* Read more about handling dismissals below */
                if (result.dismiss === Swal.DismissReason.timer) {
                    console.log('I was closed by the timer')
                }
            })
         });
        // $(".chosen-select").chosen().change( function () { alert("change"); } );
    });


    function previewImage() {
        const image = document.querySelector('#image');
        const imgPreview = document.querySelector('.img-preview');

        imgPreview.style.display = 'block';

        const oFReader = new FileReader();
        oFReader.readAsDataURL(image.files[0]);

        oFReader.onload = function(oFREvent) {
        imgPreview.src = oFREvent.target.result;
    }
  }

</script>
@endpush

resources/views/layanan/detail_layanan/edit.blade.php
@extends('admin.main')

@section('content')
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title mb-1"><b>Layanan</b></h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Layanan</li>
                        <li class="breadcrumb-item active"><a href="/dashboard/layanan/detail_layanan">Detail Layanan</a></li>
                        <li class="breadcrumb-item active">Form Detail Layanan</li>
                    </ol>
                </div><!--end col-->
            </div><!--end row-->                                                              
        </div><!--end page-title-box-->
    </div><!--end col-->
</div><!--end row-->
<div class="col-md-12 pt-3 pb-2 mb-3" style="background-color: white;">
    <div class="box">
        <div class="col-lg-8" style="margin: auto">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Form Detail Layanan</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route('detail_layanan.update', $detail->id) }}" method="post" enctype="multipart/form-data">
                        @method('put')
                        @csrf
                        <div class="form-group">
                            <label for="service" class="form-label">Ganti Layanan</label>
                            <div class="input-group">
                                <select name="service" id="service" class="form-control mb-4">
                                    <option value="">-- Pilih Layanan --</option>
                                    @foreach ($services as $service)
                                        @if(old('service', $detail->service_id) == $service->id)
                                            <option value="{{ $service->id }}" selected>{{ $service->title }}</option>
                                        @else
                                            <option value="{{ $service->id }}">{{ $service->title }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                            @error('service')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="mb-4 p-3" style="border: 1px dotted black;">
                            <p class="text-center">Form untuk bagian depan halaman</p>
                        
                            <div class="mb-2">
                                <label for="question" class="form-label">Pertanyaan Mengenai Layanan</label>
                                <input type="text" class="form-control mb-3 @error('question') is-invalid @enderror" id="question" name="question" value="{{ old('question', $detail->question) }}" required maxlength="255">
                                @error('question')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                @enderror
                                <div class="mb-2">
                                    <label for="image" class="form-label">Gambar</label>
                                    <input type="file" class="form-control @error('image') is-invalid @enderror" id="image"
                                        name="image" onchange="previewImage()" value="{{ old('image', $detail->image) }}">
                                    <input type="hidden" name="oldImage" id="oldImage" value="{{ $detail->image }}">
                                    @if($detail->image)
                                        <img src="{{ asset('storage/'. $detail->image) }}" class="img-preview img-fluid my-3 col-sm-5 d-block">
                                    @else
                                        <img class="img-preview img-fluid my-3 col-sm-5">
                                    @endif
                                    @error('image')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
    
                                <div class="col-lg-12 mb-2">
                                    <div class="col-lg-12 mb-2">
                                        <label for="answer" class="form-label">Jawaban</label>
                                        @error('answer')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                        <input type="hidden" class="form-control" id="answer" name="answer" value="{{ old('answer', $detail->answer) }}" maxlength="255">
                                    <trix-editor input="answer"></trix-editor>
                                </div>
                            </div>
                        </div>
                        <div class="form-group mt-4">
                            <label for="name">Jasa</label>
                            <select name="jasa[]" id="jasa" class="form-control chosen-select" multiple>
                                @foreach($jasa as $key => $j)
                                    <option value="{{ $j->id }}" 
                                        @if(!empty($detail)) 
                                            @foreach($detail->jasa as $jasa)
                                                @if($jasa->id == $j->id)
                                                    selected
                                                @endif
                                            @endforeach
                                        @endif
                                        >{{ ++$key }}. {{ $j->title }}
                                    </option>
                                @endforeach
                            </select>
                            @error('jasa')
                            <b class="text-danger">{{ $message }}</b>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="advantage" class="form-label">Keunggulan</label>
                            <div class="input-group">
                                <select name="advantage[]" id="feature" multiple class="chosen-select form-control mb-4">
                                    @foreach ($advantage as $key => $item)
                                    <option value="{{ $item->id }}"
                                    @if(!empty($detail))
                                        @foreach($detail->advantage as $a)
                                            @if($a->id == $item->id)
                                                selected
                                            @endif
                                        @endforeach
                                    @endif
                                    >{{ ++$key }}. {{ $item->advantage }}</option>
                                    @endforeach
                                </select>
                            </div>
                            @error('advantage')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="package" class="form-label">Paket</label>
                            <div class="input-group">
                                <select name="package[]" id="feature" multiple class="chosen-select form-control mb-4">
                                    @foreach ($package as $key => $item)
                                    <option value="{{ $item->id }}"
                                    @if(!empty($detail))
                                        @foreach(@$detail->package as $p)
                                            @if($p->id == $item->id)
                                                selected
                                            @endif
                                        @endforeach
                                    @endif
                                    >{{ ++$key }}. {{ $item->name }}</option>
                                    @endforeach
                                </select>
                                <span class="placeholder col-12 bg-light">MAX 3 Select : Kiri | Tengah | Kanan</span>
                            </div>
                            @error('package')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="/dashboard/layanan/detail_layanan" class="btn btn-danger">Kembali</a>
                    </form>                                           
                </div><!--end card-body-->
            </div><!--end card-->
        </div><!--end col-->
    </div>
</div>
@endsection

@push('script')
<script>

    $(document).ready(function () {
        $(".chosen-select-deselect").chosen({allow_single_deselect:true});
        $(".chosen-select").chosen({ max_selected_options:3});
        $(".chosen-select").bind("chosen:maxselected", function () { 
            let timerInterval
            Swal.fire({
                title: 'Max Selected is 3!',
                html: '<b></b>',
                timer: 1650,
                timerProgressBar: true,
                didOpen: () => {
                    Swal.showLoading()
                    const b = Swal.getHtmlContainer().querySelector('b')
                    timerInterval = setInterval(() => {
                    b.textContent = Swal.getTimerLeft()
                    }, 100)
                },
                willClose: () => {
                    clearInterval(timerInterval)
                }
                }).then((result) => {
                /* Read more about handling dismissals below */
                if (result.dismiss === Swal.DismissReason.timer) {
                    console.log('I was closed by the timer')
                }
            })
         });
        // $(".chosen-select").chosen().change( function () { alert("change"); } );
    });

    function previewImage() {
        const image = document.querySelector('#image');
        const imgPreview = document.querySelector('.img-preview');

        imgPreview.style.display = 'block';

        const oFReader = new FileReader();
        oFReader.readAsDataURL(image.files[0]);

        oFReader.onload = function(oFREvent) {
        imgPreview.src = oFREvent.target.result;
    }
  }

</script>
@endpush