routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\{
    DashboardController,
    AuthController,
};

use App\Http\Controllers\LogoBrandingController;
use App\Http\Controllers\DesignFeedInstagramController;
use App\Http\Controllers\DigitalMarketingController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SMMController;
use App\Http\Controllers\MarketingCommunicationsController;

use App\Http\Controllers\AdvantageController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DetailPageController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\DetailServiceController;
use App\Http\Controllers\JasaController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\PackageFeatureController;
use App\Http\Controllers\PortofolioController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TestimonialController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SitemapController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');
Route::get('/check', [HomeController::class, 'check'])->name('home.check');

Route::get('/articles', [PostsController::class, 'index'])->name('posts.index');

Route::get('/layanan/{slug}', [DetailPageController::class, 'index'])->name('detail_page.index');
Route::get('/article/{slug}', [PostController::class, 'index'])->name('post.index');

Route::get('/sitemap', [SitemapController::class, 'index']);

// FrontEnd UI/UX
    // Logo Branding
    // Route::get('/logobranding', [LogoBrandingController::class, 'index'])->name('logobranding.index');

   // Design Feed Instagram
    // Route::get('/designfeed', [DesignFeedInstagramController::class, 'index'])->name('designfeed.index');

    // Digital Marketing
    // Route::get('/digitalmarketing', [DigitalMarketingController::class, 'index'])->name('digitalmarketing.index');

    // Social MM
    // Route::get('/smm', [SMMController::class, 'index'])->name('smm.index');

    // Marketing Communications
    // Route::get('/marketingcommunications', [MarketingCommunicationsController::class, 'index'])->name('marketing.index');

    // Login Dashboard
    Route::get('/auth/login', [AuthController::class, 'auth'])->name('auth.index');
    Route::post('/auth/process', [AuthController::class, 'process'])->name('auth.process');

// Disini untuk admin
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'dashboard']);

    // Rute Semua Layanan

        // Slug Service 
        Route::get('/dashboard/layanan/service/makeSlug', [ServiceController::class, 'makeSlug'])->middleware('auth');

        // Service
        Route::resource('/dashboard/layanan/service', ServiceController::class);
        Route::post('/dashboard/layanan/service/data', [ServiceController::class, 'data'])->name('service.data');

        // Service - Sub (What are the Service are)
        Route::resource('/dashboard/layanan/jasa', JasaController::class);
        Route::post('/dashboard/layanan/jasa/data', [JasaController::class, 'data'])->name('jasa.data');

         // Detail Services
         Route::resource('/dashboard/layanan/detail_layanan', DetailServiceController::class);
         Route::post('/dashboard/layanan/detail_layanan/data', [DetailServiceController::class, 'data'])->name('detail_service.data');
         Route::get('/dashboard/layanan/detail_layanan/{id}/edit', [DetailServiceController::class, 'ubah'])->name('detail_layanan.ubah');
         Route::delete('/dashboard/layanan/detail_layanan/{id}/hapus', [DetailServiceController::class, 'hapus'])->name('detail_service.hapus');
    //

    // Article
    Route::resource('/dashboard/article', ArticleController::class);
    Route::post('/dashboard/article/table', [ArticleController::class, 'table'])->name('article.table');
        
    // Testimonial
    Route::resource('/dashboard/testimonial', TestimonialController::class);
    Route::post('/dashboard/testimonial/data', [TestimonialController::class, 'data'])->name('testimonial.data');

    // Portofolio
    Route::resource('/dashboard/portofolio', PortofolioController::class);
    Route::post('/dashboard/portofolio/data', [PortofolioController::class, 'data'])->name('portofolio.data');

    //Package
    Route::resource('dashboard/package', PackageController::class);
    Route::post('/dashboard/package/data', [PackageController::class, 'data'])->name('package.data');
    //Feature
    Route::resource('dashboard/feature', FeatureController::class);
    Route::post('/dashboard/feature/data', [FeatureController::class, 'data'])->name('feature.data'); 

    // Client
    Route::resource('/dashboard/client', ClientController::class);
    Route::post('/dashboard/client/data', [ClientController::class, 'data'])->name('client.data');

    //Feature
    Route::resource('dashboard/feature', FeatureController::class);
    Route::post('/dashboard/feature/data', [FeatureController::class, 'data'])->name('feature.data');

    //Advantage or Previllege
    Route::resource('/dashboard/advantage', AdvantageController::class);
    Route::post('/dashboard/advantage/data', [AdvantageController::class, 'data'])->name('advantage.data');

    //Categories
    // Route::resource('/dashboard/categories', CategoriesController::class);
    // Route::get('/dashboard/categories/{id}/edit', [CategoriesController::class, 'edid'])->name('categories.edid');
    // Route::put('/dashboard/categories/update', [CategoriesController::class, 'apded'])->name('categories.apded');
    // Route::post('/dashboard/categories/data', [CategoriesController::class, 'data'])->name('categories.data');
    // Route::delete('/dashboard/categories/{id}/hapus', [CategoriesController::class, 'hapus'])->name('categories.hapus');
    
     // Category
     Route::resource('dashboard/categories', CategoryController::class);
     Route::post('/dashboard/categories/data', [CategoryController::class, 'data'])->name('category.data');
 

    // Article
    Route::resource('/dashboard/article', ArticleController::class);
    Route::post('/dashboard/article/data', [ArticleController::class, 'data'])->name('article.data');
        // Slug Service 
        Route::get('/dashboard/article/articleSlug', [ServiceController::class, 'articleSlug'])->middleware('auth');

    // User
    Route::resource('dashboard/user', UserController::class);
    Route::post('/dashboard/user/data', [UserController::class, 'data'])->name('user.data');

    //Setting
    Route::resource('/dashboard/setting', SettingController::class);
    Route::put('/dashboard/setting/{id}/setting_home', [SettingController::class, 'updateHome'])->name('setting.updateHome');
    Route::put('/dashboard/setting/{id}/setting_dashboard', [SettingController::class, 'updateDashboard'])->name('setting.updateDashboard');

    //Logout
    Route::get('/auth/logout', [AuthController::class, 'logout'])->name('auth.logout');    
    
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Foundation\Auth\User as AuthUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        return view('user.index', compact('user'));

    }

    public function data()
    {
        $user = User::orderBy('id', 'desc')->get();

        return datatables()
            ->of($user)
            ->addIndexColumn()
            ->addColumn('name', function($user) {
                return $user->name;
            })
            ->addColumn('username', function($user) {
               return $user->username;
            })
            ->addColumn('action', function ($user) {
                return '
                    <a href="'. route('user.edit', $user->id) .'" class="btn btn-xs bg-warning"><i class="fa-solid fa-pen-to-square"></i></a>
                    <button onclick="deleteData(`'. route('user.destroy', $user->id) .'`)" class="btn btn-xs btn-danger btn-flat delete"><i class="fa-solid fa-trash-can"></i></button>
                ';
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create', [
            'user' => User::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $user = new User();
        $user->name = $request->name;
        $user->username = $request->username;
        $user->password = bcrypt($request->password);

        $user->save();

        // return redirect('/dashboard/user')->response()->json('Data berhasil disimpan', 200);
        return redirect()->route('user.index')->with(['success' => 'Berhasil Disimpan!']);
        // return redirect('/dashboard/user')->with('success', 'Pengguna baru berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // return User::find($id);

        return view('user.edit', [
            'user' => User::find($id),
            'users' => User::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        $user = User::find($id);
        // $user->name = $request->name;
        // $user->username = $request->username;
        // $user->password = bcrypt($request->password);

        // $user = auth()->user();
        
        $user->name = $request->name;
        $user->username = $request->username;

        if ($request->has('password') && $request->password != "") {
            if (Hash::check($request->old_password, $user->password)) {
                if ($request->password == $request->password_confirmation) {
                    $user->password = bcrypt($request->password);
                } else {
                    return redirect('/dashboard/user')->with('error', 'Konfirmasi password tidak sesuai!');
                }
            } else {
                return redirect('/dashboard/user')->with('error', 'Password lama tidak sesuai!');
            }
        }

        $user->update();

        return redirect()->route('user.index')->with(['success' => 'Berhasil Diperbarui!']);
        // return redirect('/dashboard/user')->with('success', 'Pengguna berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        User::destroy($user->id);

        return redirect()->route('user.index')->with(['success' => 'Berhasil Dihapus!']);
        // return redirect('/dashboard/user')->with('success', 'Pengguna berhasil dihapus');
    }
}

resources/views/user/create.blade.php
@extends('admin.main')

@section('content')
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title mb-1"><b>Pengguna</b></h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active"><a href="/dashboard">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="/dashboard/user">Pengguna</a></li>
                        <li class="breadcrumb-item active">Form Pengguna</li>
                    </ol>
                </div><!--end col-->
            </div><!--end row-->                                                              
        </div><!--end page-title-box-->
    </div><!--end col-->
</div><!--end row-->
<div class="col-md-12 pt-3 pb-2 mb-3" style="background-color: white;">
    <div class="box">
        <div class="col-lg-8" style="margin: auto">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Form Pengguna</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route('user.store') }}" method="post" id="user-form">
                        @csrf
                        <div class="form-group">
                            <label for="name" class="form-label">Nama</label>
                            <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                                name="name" value="{{ old('name') }}" required>
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control @error('username') is-invalid @enderror" id="username"
                                name="username" value="{{ old('username') }}" required>
                            @error('username')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control @error('password') is-invalid @enderror" id="password"
                                name="password" value="{{ old('password') }}" required minlength="4">
                            @error('password')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="/dashboard/user" class="btn btn-danger">Kembali</a>
                    </form>                                           
                </div><!--end card-body-->
            </div><!--end card-->
        </div><!--end col-->
    </div>
</div>
@endsection

@push('script')
<script>
     $('#user-form').validator().on('submit', function (e) {
        if (! e.preventDefault()) {
            $.post($('#user-form').attr('action'), $('#user-form form').serialize());
                if((response == true) => {
                    Swal.fire({
                        title: 'Sukses!',
                        text: response,
                        icon: 'success',
                        confirmButtonText: 'Lanjut',
                        confirmButtonColor: '#28A745'
                    })
                    window.location('/dashboard/user');
                })
                else((response ) => {
                    Swal.fire({
                        title: 'Gagal!',
                        text: 'Data Produk yang diinput sudah ada',
                        icon: 'error',
                        confirmButtonText: 'Kembali',
                        confirmButtonColor: '#DC3545'
                    })
                    table.ajax.reload();
    
                    return;
                });
        }
    });
</script>
    
@endpush

resources/views/user/edit.blade.php
@extends('admin.main')

@section('content')
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title mb-1"><b>Pengguna</b></h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active"><a href="/dashboard">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="/dashboard/user">Pengguna</a></li>
                        <li class="breadcrumb-item active">Form Pengguna</li>
                    </ol>
                </div><!--end col-->
            </div><!--end row-->                                                              
        </div><!--end page-title-box-->
    </div><!--end col-->
</div><!--end row-->
<div class="col-md-12 pt-3 pb-2 mb-3" style="background-color: white;">
    <div class="box">
        <div class="col-lg-8" style="margin: auto">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Form Pengguna</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route('user.update', $user) }}" method="post">
                        @method('put')
                        @csrf
                        <div class="form-group">
                            <label for="name" class="form-label">Nama</label>
                            <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                                name="name" value="{{ old('name', $user->name) }}">
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control @error('username') is-invalid @enderror" id="username"
                                name="username" value="{{ old('username', $user->username) }}">
                            @error('username')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="old_password" class="form-label">Password Lama</label>
                            <input type="password" name="old_password" class="form-control  @error('old_password') is-invalid @enderror " id="old_password"  
                            minlength="4">
                            <div class="col-sm-4">
                                <span class="help-block with-errors"></span>
                                @error('old_password')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password" class="form-label">Password Baru</label>
                            <input type="password" name="password" class="form-control  @error('password') is-invalid @enderror " id="password"  
                            minlength="4">
                            <div class="col-sm-4">
                                <span class="help-block with-errors"></span>
                                @error('password')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password_confirmation" class="form-label">Konfirmasi Password</label>
                            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control  @error('password_confirmation') is-invalid @enderror "  
                            data-match="#password" minlength="4">
                            <div class="col-sm-4">
                                <span class="help-block with-errors"></span>
                                @error('password_confirmation')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="/dashboard/user" class="btn btn-danger">Kembali</a>
                    </form>                                           
                </div><!--end card-body-->
            </div><!--end card-->
        </div><!--end col-->
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('admin.main')

@section('content')
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title mb-1"><b>Pengguna</b></h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active"><a href="/dashboard">Dashboard</a></li>
                        <li class="breadcrumb-item active">Pengguna</li>
                    </ol>
                </div><!--end col-->
            </div><!--end row-->                                                              
        </div><!--end page-title-box-->
    </div><!--end col-->
</div><!--end row-->
<div class="col-md-12 p-2 mb-3" style="background-color: white">

        {{-- @if(session()->has('success'))
        <div class="p-3 bg-success text-white" id="alert">{{ session()->get('success') }}</div>
        @endif --}}

        @if(session()->has('error'))
        <div class="p-3 bg-danger text-white" id="alert">{{ session()->get('error') }}</div>
        @endif

        <div class="box">
            <div class="box-header with-border mx-2">
                <h2 class="my-5 text-center">Pengguna</h2>
                <a href="/dashboard/user/create" class="btn btn-outline-dark mb-3 p-2">
                    Tambah Baru
                    <span data-feather="plus-circle"></span>
                </a>
            </div>

            <div class="box-body table-responsive">
                <table class="table table-bordered table-user">
                    <thead>
                        <tr>
                            <th scope="col" class="text-center table-default" style="color:black;" width="6%">No</th>
                            <th scope="col" class="text-center table-default" style="color:black;">Nama</th>
                            <th scope="col" class="text-center table-default" style="color:black;">Username</th>
                            <th width="10%" scope="col" class="text-center table-default" style="color:black;"> <i class="fas fa-regular fa-gears"></i></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
</div>
@endsection

@push('script')
<script> 
    var time = document.getElementById("alert");

    setTimeout(function(){
    time.style.display = "none";
    }, 3000);

    let table;
        table = $('.table-user').DataTable({
        processing: true,
        responsive: true,
        autoWidth: false,
        serverSide: true,
        ajax: {
            url: "{{ route('user.data') }}",
            type: "POST",
            data: {  
                _token: '{{ csrf_token() }}'
            }
        },
        columns: [
            {data:'DT_RowIndex', searchable: false, sortable: false},
            {data:'name'},
            {data:'username'},
            {data:'action', searchable: false, sortable: false},
        ]
    });

    function deleteData(url) {
        Swal.fire({
            title: 'Hapus Pengguna yang dipilih?',
            icon: 'question',
            iconColor: '#DC3545',
            showDenyButton: true,
            denyButtonColor: '#838383',
            denyButtonText: 'Batal',
            confirmButtonText: 'Hapus',
            confirmButtonColor: '#DC3545'
            }).then((result) => {
            if (result.isConfirmed) {
                $.post(url, {
                    '_token': $('[name=csrf-token]').attr('content'),
                    '_method': 'delete'
                })
                .done((response) => {
                    Swal.fire({
                        title: 'Sukses!',
                        text: 'Pengguna berhasil dihapus',
                        icon: 'success',
                        confirmButtonText: 'Lanjut',
                        confirmButtonColor: '#28A745'
                    }) 
                    table.ajax.reload();
                })
                .fail((errors) => {
                    Swal.fire({
                        title: 'Gagal!',
                        text: 'Pengguna gagal dihapus',
                        icon: 'error',
                        confirmButtonText: 'Kembali',
                        confirmButtonColor: '#DC3545'
                    })                       
                    return;
                });
            } else if (result.isDenied) {
                Swal.fire({
                    title: 'Pengguna batal dihapus',
                    icon: 'warning'
                })
            }
        })
    }
</script> 
@endpush